[package]
name          = "cw5144"
description   = "Definition and types for the CosmWasm-5144 SBT interface"
authors       = [
  "Georges Chouchani <georges@athenaconsulting.io>",

]
version       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-utils        = { workspace = true }
schemars        = { workspace = true }
serde           = { workspace = true }
